### ISSUE TITLE
Definition of "moderation" in the IETF context

### ISSUE THREAD

**Issue by paulehoffman** [larseggert/moderation#36]
The draft does not define what the moderator team is and is not allowed to do. This is important because online moderation normally involves removing posting, whereas in the IETF context it only means limiting new posting by an individual. If this draft intends to allow removing of messages from mailing list archives (and I sincerely hope it doesn't!), it needs to say so clearly. If it doesn't intend to allow removing of messages from mailing list archives, it needs to say that so that readers outside the IETF context understand that this is different than all the social media platforms they are familiar with.

**Comment by becarpenter** [comment]
I think we do very occasionally remove messages that are clearly criminal or utterly unacceptable. Certainly we need that option, for legal reasons if no other, but I agree that we need a definition of "normal" moderation.

**Comment by larseggert** [comment]
There is a TODO in the current revision on whether the document should define some fenceposts for moderation. (Removing messages from the archives is typically done because of legal risks, i.e., is an LLC decision.)

**Comment by paulehoffman** [comment]
Good enough that you have a TODO. I'll close the issue.
