### ISSUE TITLE
Scaling (1)

### ISSUE THREAD

**Issue by becarpenter** [larseggert/moderation#45]
The draft has two TODOs that amount to the same thing: "Decide whether moderation rights remain also with WG chairs, list admins,..."

This is a scaling issue: there is no way that a small team can pro-actively moderate hundreds of lists. So it seems evident to me that existing list admins must be the first line (whether for WG or non-WG lists). The only exceptions might be a handful of IETF-wide lists, notably ietf@ and last-call@ (as the draft already says).

Of course that interacts with the BCP83 discussion.

**Comment by larseggert** [comment]
That WFM, but then we should make it clear(er) that chairs (and community members?) MAY/SHOULD inform the moderators about potentially problematic behavior.

**Comment by becarpenter** [comment]
Yes, indeed, I guess it's SHOULD for chairs and non-WG list admins, and MAY for the community.
