### ISSUE TITLE
Scaling (2)

### ISSUE THREAD

**Issue by becarpenter** [larseggert/moderation#46]
> This IETF moderator team consists of a small number of individuals (no less than three)

Three is certainly too small. Perhaps change it to "(no less than five)", or omit the parenthesis completely to avoid micromanagement.

**Comment by larseggert** [comment]
Yes, that trips people up constantly. Maybe
```
This IETF moderator team consists of no less than three individuals,
to establish some minimum basis for consensus-based team decisions
and geographic spread, but realistically needs to have several times that
number of members to spread the moderation load and provide redundancy
in the cases of absences, etc.
```

**Comment by JayDaley** [comment]
If you have several time 3, i.e. 21, then do they all need to reach consensus on any decision?

**Comment by larseggert** [comment]
I didn't mean we need always a multiple of three, just maybe a bunch more than just three. Point about consensus remains.

**Comment by becarpenter** [comment]
I don't we should set a hard minimum or a hard maximum. Common sense should apply.
