### ISSUE TITLE
Define "moderate"

### ISSUE THREAD

**Issue by becarpenter** [larseggert/moderation#47]
We need to precisely define what we mean by "moderate" and "moderation".

See this message for context:
https://mailarchive.ietf.org/arch/msg/gendispatch/i74Ey8_aFRqekH4n2d6Ha412hSk/

**Comment by larseggert** [comment]
Yes, we should be explicit about this being a spectrum all the way from gentle reminders on- and off-list, all the way to suspension of posting rights and other ways of participating/communicating.

We need to make sure the I-D doesn't go to far into policy-setting territory though; that IMO the team needs to do for itself.

**Comment by becarpenter** [comment]
Maybe state something like: The term "moderation" can refer both to _preemptive_ moderation, where a moderator reviews messages before release to the mailing list, and _reactive_ moderation, where the moderator intervenes after a message has been sent. The IETF mainly practices reactive moderation, with a spectrum all the way from gentle reminders on- and off-list, all the way to suspension of posting rights and other ways of participating/communicating.

PR?

**Comment by larseggert** [comment]
WFM. Yes, PR please?
