### ISSUE TITLE
Emergency actions for egregious postings

### ISSUE THREAD

**Issue by becarpenter** [larseggert/moderation#51]
I think we should explicitly authorise a few people to take emergency action when a completely unacceptable posting is made (illegal, vulgar, or manifestly harassing). For example, the IETF Chair, the Exec Dir, and maybe a couple of backups, could instruct staff to delete a given message and/or block a given poster, subject to follow-up within 48 hours by the moderation team or to referral to the Ombudsteam.

(I think the staff already have discretion to delete manifest spam, but I'm not sure where that is written down.)

**Comment by larseggert** [comment]
Agree. But we also need to handle the case where a participation channel gets DoS'ed.

**Comment by becarpenter** [comment]
Yes, staff must be able to respond immediately to DoS without any delay.

**Comment by larseggert** [comment]
Based on experience, staff will very often want sign-off from leadership or the community.

**Comment by becarpenter** [comment]
Yes, that makes sense, but we need language that allows for true emergencies,
